# Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

---

#### array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## import numpy

import numpy as np

In [2]:
# Create an array of list elements
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [11]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
type(arr)

numpy.ndarray

In [14]:
## check the shape of the array

arr.shape

(3, 5)

### Indexing 

In [28]:
## Accessing the array elements

arr

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [9, 7, 6, 8, 9]]

In [29]:
arr[2]

[9, 7, 6, 8, 9]

In [31]:
arr = [1,2,3,4,5,6]
arr[2:]=[100]

In [32]:
arr

[1, 2, 100]

In [18]:
arr = [[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]]
arr1 = np.array(arr)

In [19]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [20]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [33]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]

array([1, 2])

In [37]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
arr1=np.arange(0,10).reshape(2,5)

In [40]:
arr2=np.arange(0,10).reshape(2,5)

In [41]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [45]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
## random distribution
np.random.rand(3,3)

array([[0.80892282, 0.71540909, 0.61908994],
       [0.47289906, 0.81495189, 0.37922198],
       [0.98095096, 0.17323863, 0.6673249 ]])

In [33]:
arr_ex=np.random.randn(4,4)

In [34]:
arr_ex

array([[-0.2816708 ,  0.46713705,  1.07500161, -0.03176097],
       [-0.34376865,  1.54154544, -1.01150133, -0.0877125 ],
       [-0.91917317,  0.85880151, -1.03365909, -0.81057992],
       [-0.47354033, -0.77474486,  0.67605319,  0.33606734]])

In [37]:
np.random.randint(0,100,8).reshape(4,2)

array([[17, 55],
       [18,  9],
       [49, 44],
       [55, 12]])

In [38]:
np.random.random_sample((1,5))

array([[0.08071418, 0.96566975, 0.96883424, 0.08489637, 0.49647535]])